 version: 2
 workflows:
   version: 2
   test:
     jobs:
       - test-categories
 jobs:
   test-auth:
     docker:
       - image: circleci/python:3.8.0
     steps:
       - checkout
       - run: python ynab/test/auth.py
   test-categories:
     docker:
       - image: circleci/python:3.8.0
     steps:
       - checkout
       - run: python ynab/tests/categories.py
