 version: 2
 workflows:
   version: 2
   test:
     jobs:
       - test-api
 jobs:
   test-api:
     docker:
       - image: circleci/python:3.8.0
     steps:
       - checkout
       - run: python -m ynab.tests.test_api
