version: 2
workflows:
  version: 2
  test:
    jobs:
      - test_core
      - test_account_api
  build:
    jobs:
      - build
jobs:
  test_core:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: python -m tests.test_core
  test_account_api:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: python -m tests.test_account_api
  build:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: sudo python setup.py sdist bdist_wheel
      - store_artifacts:
        path: dist
